name: Build Zip

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: Build Zip
    runs-on: ubuntu-20.04

    env:
      RELEASE_FILE: enviro

    steps:
    - uses: actions/checkout@v2
      with:
        path: enviro
        submodules: true

    - name: Prepare repository
      shell: bash
      run: |
        rm -rf enviro/.git*
        rm -rf enviro/phew/.git*

    - uses: vimtor/action-zip@v1
      with:
        files: enviro/
        dest: ${{env.RELEASE_FILE}}.zip

    - name: Store .zip as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.RELEASE_FILE}}
        path: enviro/

    - name: Upload .zip
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        asset_path: ${{env.RELEASE_FILE}}.zip
        upload_url: ${{github.event.release.upload_url}}
        asset_name: ${{env.RELEASE_FILE}}.zip
        asset_content_type: application/octet-stream